In [1]:
import numpy as np


In [3]:
myList = [2, 3, 5, 7, 11]
myArray = np.array([2, 3, 5, 7, 11])
print(type(myList))
print(type(myArray))
print(myList)
print(myArray)

<class 'list'>
<class 'numpy.ndarray'>
[2, 3, 5, 7, 11]
[ 2  3  5  7 11]


In [6]:
integers = np.array([[1,2,3],[4,5,6]])
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
print(integers)
print(integers.dtype)
print(floats.dtype)

[[1 2 3]
 [4 5 6]]
int32
float64


In [5]:
print(integers.ndim)
print(floats.ndim)
print(integers.shape)
print(floats.shape)

2
1
(2, 3)
(5,)


In [7]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


In [8]:
for i in integers.flat:
    print(i, end='  ')

1  2  3  4  5  6  

In [9]:
arr0s = np.zeros(5)
arr1s = np.ones((3,4))
arrvals = np.full((2,3), 5.5)
print(arr0s)
print()
print(arr1s)
print()
print(arrvals)

[0. 0. 0. 0. 0.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[5.5 5.5 5.5]
 [5.5 5.5 5.5]]


In [10]:
print(np.arange(5))
print(np.arange(5, 10))
print(np.arange(10, 1, -2))

[0 1 2 3 4]
[5 6 7 8 9]
[10  8  6  4  2]


In [11]:
print(np.linspace(0.0, 1.0, num=5))

[0.   0.25 0.5  0.75 1.  ]


In [12]:
print(np.arange(1,1))
print(np.arange(1,13).reshape(3,4))

[]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(np.arange(1, 100001).reshape(4, 25000))

[[     1      2      3 ...  24998  24999  25000]
 [ 25001  25002  25003 ...  49998  49999  50000]
 [ 50001  50002  50003 ...  74998  74999  75000]
 [ 75001  75002  75003 ...  99998  99999 100000]]


In [14]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [15]:
from datetime import datetime
print(datetime.now())
print(type(datetime.now()))

2024-02-10 19:35:52.071872
<class 'datetime.datetime'>


In [21]:
from time import sleep
start = datetime.now()
sleep(1)
end= datetime.now()
print((end-start).total_seconds())
print(end - start)

1.000614
0:00:01.000614


In [33]:
start=datetime.now()
rolls_array = np.random.randint(1, 7, 60_000_000)
end=datetime.now()
print((end-start).total_seconds())

0.494901


In [35]:
start = datetime.now()
rolls_array = np.random.randint(1, 7, 600_000_000)
end = datetime.now()
print((end-start).total_seconds())

5.760864


In [36]:
numbers = np.arange(1, 6)
print(numbers)
print(numbers*2)
print(numbers**3)

[1 2 3 4 5]
[ 2  4  6  8 10]
[  1   8  27  64 125]


In [37]:
numbers += 10
print(numbers)

[11 12 13 14 15]


In [38]:
numbers2 = np.linspace(1.1, 5.5, 5)
numbers3 = [10,10,10,10,10]
print(numbers2*10)
print(numbers2*numbers3)

[11. 22. 33. 44. 55.]
[11. 22. 33. 44. 55.]


In [39]:
print(numbers)
print(numbers2)
print(numbers>=13)
print(numbers2>=13)

[11 12 13 14 15]
[1.1 2.2 3.3 4.4 5.5]
[False False  True  True  True]
[False False False False False]


In [40]:
print(numbers > numbers)
print(numbers == numbers)

[False False False False False]
[ True  True  True  True  True]


In [42]:
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])
print(grades.sum())
print(grades.min())
print(grades.max())
print(grades.mean())
print(grades.std())
print(grades.max(axis=0))
print(grades.mean(axis=1))

1054
70
100
87.83333333333333
8.792357792739987
[100  96  90]
[84.33333333 92.33333333 87.         87.66666667]


In [43]:
numbers = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(numbers))
print(np.log2(numbers))


[1. 2. 3. 4. 5. 6.]
[0.         2.         3.169925   4.         4.64385619 5.169925  ]


In [45]:
print(grades)
print(grades[0,1])
print(grades[1,:])  # the comma here signifies the entire second subarray
print(grades[:,2])  # the comma here signifies the entire arrays third position in each subset

[[ 87  96  70]
 [100  87  90]
 [ 94  77  90]
 [100  81  82]]
96
[100  87  90]
[70 90 90 82]


In [66]:
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])
#print(grades[::])
#print(grades[0:2,:])
#print(grades[:, [0,2]])
print(grades[[0,3],1:3])

[[96 70]
 [81 82]]
