In [1]:
import numpy as np


In [3]:
myList = [2, 3, 5, 7, 11]
myArray = np.array([2, 3, 5, 7, 11])
print(type(myList))
print(type(myArray))
print(myList)
print(myArray)

<class 'list'>
<class 'numpy.ndarray'>
[2, 3, 5, 7, 11]
[ 2  3  5  7 11]


In [6]:
integers = np.array([[1,2,3],[4,5,6]])
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
print(integers)
print(integers.dtype)
print(floats.dtype)

[[1 2 3]
 [4 5 6]]
int32
float64


In [5]:
print(integers.ndim)
print(floats.ndim)
print(integers.shape)
print(floats.shape)

2
1
(2, 3)
(5,)


In [7]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


In [8]:
for i in integers.flat:
    print(i, end='  ')

1  2  3  4  5  6  

In [9]:
arr0s = np.zeros(5)
arr1s = np.ones((3,4))
arrvals = np.full((2,3), 5.5)
print(arr0s)
print()
print(arr1s)
print()
print(arrvals)

[0. 0. 0. 0. 0.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[5.5 5.5 5.5]
 [5.5 5.5 5.5]]


In [10]:
print(np.arange(5))
print(np.arange(5, 10))
print(np.arange(10, 1, -2))

[0 1 2 3 4]
[5 6 7 8 9]
[10  8  6  4  2]


In [11]:
print(np.linspace(0.0, 1.0, num=5))

[0.   0.25 0.5  0.75 1.  ]


In [12]:
print(np.arange(1,1))
print(np.arange(1,13).reshape(3,4))

[]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(np.arange(1, 100001).reshape(4, 25000))

[[     1      2      3 ...  24998  24999  25000]
 [ 25001  25002  25003 ...  49998  49999  50000]
 [ 50001  50002  50003 ...  74998  74999  75000]
 [ 75001  75002  75003 ...  99998  99999 100000]]


In [14]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [15]:
from datetime import datetime
print(datetime.now())
print(type(datetime.now()))

2024-02-10 19:35:52.071872
<class 'datetime.datetime'>


In [21]:
from time import sleep
start = datetime.now()
sleep(1)
end= datetime.now()
print((end-start).total_seconds())
print(end - start)

1.000614
0:00:01.000614


In [33]:
start=datetime.now()
rolls_array = np.random.randint(1, 7, 60_000_000)
end=datetime.now()
print((end-start).total_seconds())

0.494901


In [35]:
start = datetime.now()
rolls_array = np.random.randint(1, 7, 600_000_000)
end = datetime.now()
print((end-start).total_seconds())

5.760864
