In [1]:
odd_nums = [1, 3, 5, 7, 9]
colors = ['red', 'orange', 'yellow', 'green', 'blue']
coord2x2 = {(1,1),(1,2),(2,1),(2,2)}
print(odd_nums)
print(colors)
print(coord2x2)

[1, 3, 5, 7, 9]
['red', 'orange', 'yellow', 'green', 'blue']
{(1, 1), (1, 2), (2, 1), (2, 2)}


In [2]:
colors = {'blue', 'green', 'blue', 'red', 'yellow'}
print(colors)

{'blue', 'red', 'yellow', 'green'}


In [3]:
print(len(colors))

4


In [4]:
for color in colors:
    print(color.upper(), end=' ')

BLUE RED YELLOW GREEN 

In [5]:
colors.add('orange')
print(colors)
colors.add('yellow')
print(colors)

{'yellow', 'red', 'blue', 'green', 'orange'}
{'yellow', 'red', 'blue', 'green', 'orange'}


In [6]:
colors.remove('yellow')
print(colors)

{'red', 'blue', 'green', 'orange'}


In [7]:
colors.remove('grey')

KeyError: 'grey'

In [8]:
mult2 = {2, 4, 6, 8, 10, 12}
mult3 = {3, 6, 9, 12}
mult4 = {4, 8, 12}
mult2or3or4= mult2.union(mult3, mult4)
mult2and3and4 = mult2.intersection(mult3, mult4)
print(mult2or3or4)
print(mult2and3and4)

{2, 3, 4, 6, 8, 9, 10, 12}
{12}


In [9]:
lofnumbers = list(range(2, 6))
lofnumbers.extend(list(range(4,8)))
sofnumbers = set(lofnumbers)
print(lofnumbers)
print(sofnumbers)
print(list(sofnumbers))

[2, 3, 4, 5, 4, 5, 6, 7]
{2, 3, 4, 5, 6, 7}
[2, 3, 4, 5, 6, 7]


In [1]:
eset_try={}
eset_try2=set()
print(type(eset_try))
print(type(eset_try2))
print(eset_try)

<class 'dict'>
<class 'set'>
{}


In [2]:
counts = [1, 2, 2, 3, 5, 5, 6, 6, 7, 8, 9, 10, 10]
evencountsunique = {item for item in counts if item % 2 == 0}
print(evencountsunique)

{8, 2, 10, 6}


In [5]:
colors = {'blue', 'green', 'red', 'yellow'}
colors.discard('blue')
colors.discard('purple')
print(colors)

{'yellow', 'red', 'green'}


In [6]:
mult2 = {2, 4, 6, 8, 10, 12}
mult3 = {2, 6, 9, 12}
mult2not3 = mult2.difference(mult3)
mult2comp3 = mult2.symmetric_difference(mult3)
print(mult2not3)
print(mult2comp3)

{8, 10, 4}
{4, 8, 9, 10}


In [2]:
cslist = []
cslist.append({'red', 'blue', 'yellow'})
cslist.append({'purple', 'orange', 'green'})
cslist.append({'yellow', 'blue', 'red', 'yellow'})
cslist.append(cslist[0].union(cslist[1]))
print(cslist)


[{'yellow', 'red', 'blue'}, {'green', 'purple', 'orange'}, {'blue', 'red', 'yellow'}, {'green', 'blue', 'orange', 'red', 'purple', 'yellow'}]


In [7]:
for colset in cslist:
    print(f'\'orange\' in {colset}', 'orange' in colset)

'orange' in {'yellow', 'red', 'blue'} False
'orange' in {'green', 'purple', 'orange'} True
'orange' in {'blue', 'red', 'yellow'} False
'orange' in {'green', 'blue', 'orange', 'red', 'purple', 'yellow'} True


In [8]:
for colset in cslist:
    print(f'{cslist[0]} == {colset}? ', cslist[0] == colset)

{'yellow', 'red', 'blue'} == {'yellow', 'red', 'blue'}?  True
{'yellow', 'red', 'blue'} == {'green', 'purple', 'orange'}?  False
{'yellow', 'red', 'blue'} == {'blue', 'red', 'yellow'}?  True
{'yellow', 'red', 'blue'} == {'green', 'blue', 'orange', 'red', 'purple', 'yellow'}?  False


In [9]:
for colset in cslist:
    print(f'{cslist[0]} < {colset}? ', cslist[0] < colset)

{'yellow', 'red', 'blue'} < {'yellow', 'red', 'blue'}?  False
{'yellow', 'red', 'blue'} < {'green', 'purple', 'orange'}?  False
{'yellow', 'red', 'blue'} < {'blue', 'red', 'yellow'}?  False
{'yellow', 'red', 'blue'} < {'green', 'blue', 'orange', 'red', 'purple', 'yellow'}?  True


In [10]:
for colset in cslist:
    print(f'{cslist[3]} > {colset}? ', cslist[3] > colset)

{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} > {'yellow', 'red', 'blue'}?  True
{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} > {'green', 'purple', 'orange'}?  True
{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} > {'blue', 'red', 'yellow'}?  True
{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} > {'green', 'blue', 'orange', 'red', 'purple', 'yellow'}?  False


In [11]:
for colset in cslist:
    print(f'{cslist[3]} != {colset}? ', cslist[3] >= colset)

{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} != {'yellow', 'red', 'blue'}?  True
{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} != {'green', 'purple', 'orange'}?  True
{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} != {'blue', 'red', 'yellow'}?  True
{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} != {'green', 'blue', 'orange', 'red', 'purple', 'yellow'}?  True


In [12]:
for colset in cslist:
    print(f'{cslist[3]} > {colset}? ', cslist[3] > colset)

{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} > {'yellow', 'red', 'blue'}?  True
{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} > {'green', 'purple', 'orange'}?  True
{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} > {'blue', 'red', 'yellow'}?  True
{'green', 'blue', 'orange', 'red', 'purple', 'yellow'} > {'green', 'blue', 'orange', 'red', 'purple', 'yellow'}?  False


In [14]:
somenums = {1, 2, 3}
print(somenums.issubset({1, 2, 3, 7}))
print(somenums.issuperset({1, 2, 2, 1}))
print(somenums.issubset({3, 2, 1}))
print(somenums.issubset({1, 2})) 

True
True
True
False


In [17]:
mult2 = {2, 4, 6, 8, 10, 12}
mult3 = {3, 6, 9, 12, 15, 18}
mult2 |= mult3
print(mult2)

{2, 3, 4, 6, 8, 9, 10, 12, 15, 18}


In [18]:
mult2 = {2, 4, 6, 8, 10, 12}
mult3 = {3, 6, 9, 12, 15, 18}
mult2 &= mult3
print(mult2)

{12, 6}


In [19]:
mult2 = {2, 4, 6, 8, 10, 12}
mult3 = {3, 6, 9, 12, 15, 18}
mult2 -= mult3
print(mult2)

{2, 4, 8, 10}


In [20]:
mult2 = {2, 4, 6, 8, 10, 12}
mult3 = {3, 6, 9, 12, 15, 18}
mult2 ^= mult3
print(mult2)

{2, 3, 4, 8, 9, 10, 15, 18}


In [21]:
compset = {{1, 2, 3},{5, 3, 1},{1, 3, 7}}

TypeError: unhashable type: 'set'

In [22]:
compset = {frozenset({1, 2, 3}),frozenset({5,3,1}), frozenset({1,3,7})}
print(frozenset({3,2,1}) in compset)

True


In [12]:
import numpy as np
mnumbers = np.array([[1, 2, 3], [2, 4, 6]])
mnumberscopy1 = mnumbers.copy()
mnumberscopy2 = mnumbers[[0,1],0:3]
print(mnumbers)
print(mnumberscopy1)
print(mnumberscopy2)

[[1 2 3]
 [2 4 6]]
[[1 2 3]
 [2 4 6]]
[[1 2 3]
 [2 4 6]]


In [13]:
mnumbers[0,0]*=10
mnumberscopy1[0,2]+=10
mnumberscopy2[1,1]+=10
print(mnumbers)
print(mnumberscopy1)

print(mnumberscopy2)

[[10  2  3]
 [ 2  4  6]]
[[ 1  2 13]
 [ 2  4  6]]
[[ 1  2  3]
 [ 2 14  6]]


In [8]:
import numpy as np
grades = np.array([[87, 96, 70], [100, 87, 90]])
grades_rs = grades.reshape(3,2)
grades_rs[1,0] = 1000
print(grades_rs)
print(grades)

[[  87   96]
 [1000  100]
 [  87   90]]
[[  87   96 1000]
 [ 100   87   90]]


In [10]:
grades.resize(1, 6)
print(grades)
grades[0,0]=500
print(grades_rs)

[[ 500   96 1000  100   87   90]]
[[ 500   96]
 [1000  100]
 [  87   90]]


In [14]:
grades = np.array([[87, 96, 70], [100, 87, 90]])
flattened = grades.flatten()
print(grades)
print(flattened)

[[ 87  96  70]
 [100  87  90]]
[ 87  96  70 100  87  90]


In [15]:
grades[0,1] = 1000
flattened[5] = 2000
print(grades)
print(flattened)

[[  87 1000   70]
 [ 100   87   90]]
[  87   96   70  100   87 2000]


In [16]:
grades = np.array([[87, 96, 70], [100, 87, 90]])
raveled = grades.ravel()
grades[0,1] = 200
raveled[5] = 300
print(grades)
print(raveled)

[[ 87 200  70]
 [100  87 300]]
[ 87 200  70 100  87 300]
